### ISSUE TITLE
Alteração das cores do site

### ISSUE THREAD

**Issue by igortuag** [igortuag/animais-fantasticos#9]
Qual paleta de cores seria mais interessante para o site, de forma a dar uma cara mais moderna? Esta paleta usada foi exatamente a apresentada no curso.

**Comment by igortuag** [comment]
Pensei nessa paleta gerada automaticamente pelo site coolors https://coolors.co/080f0f-a4bab7-eff2c0-bea57d-a52422

**Comment by polyanetuag** [comment]
Também estou fazendo o mesmo projeto. Acredito que uma boa alternativa seria usar degradê para background de alguns elementos
